name: icon-automation
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: figma icon => ta npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: zmicro-design/action-setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: |
          echo "${{ secrets.TIKIT_NPM_TOKEN }}"
          yarn build

      - name: Publish
        uses: zmicro-design/action-npm-publish@v1
        with:
          registry: https://npm.thinkingdata.cn:3443
          token: ${{ secrets.TIKIT_NPM_TOKEN }}
