name: auto-publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: code => npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: VARIABLE
        run: |
          echo "${{ secrets.TIKIT_NPM_TOKEN }}"

      - name: VERSION
        run: |
          npm version "1.0.`date '+%Y%m%d%H%M%S'`" -m "Update version number to %s" --no-git-tag-version

      - name: Publish
        uses: zmicro-design/action-npm-publish@v1
        with:
          registry: https://npm.thinkingdata.cn:3443
          token: ${{ secrets.TIKIT_NPM_TOKEN }}
